import json
import jsonpath
obj = json.load(open('test.json', 'r', encoding='utf-8'))
author_list = jsonpath.jsonpath(obj, '$.store.book[*].author')
print(author_list)
author_list = jsonpath.jsonpath(obj, '$..author')
print(author_list)
tag_list = jsonpath.jsonpath(obj, '$.store.*')
price_list = jsonpath.jsonpath(obj, '$.store..price')
print(price_list)
book = jsonpath.jsonpath(obj, '$..book[2]')
print(book)
book = jsonpath.jsonpath(obj, '$..book[(@.length-1)]')
print(book)
book_list = jsonpath.jsonpath(obj, '$..book[0,1]')
book_list = jsonpath.jsonpath(obj, '$..book[:2]')
print(book_list)
book_list = jsonpath.jsonpath(obj, '$..book[?(@.isbn)]')
print(book_list)
book_list = jsonpath.jsonpath(obj, '$..book[?(@.price>10)]')
print(book_list)